
# SECTION 1: PREREQUISITES (DOCUMENTATION)

prerequisites:
  k3s_cluster:
    description: >
      K3s cluster must already be installed and running.
      Original HA design assumes 1 master + multiple workers.
      Actual deployment uses 1 master + 1 worker.
    nodes:
      master: 192.168.29.238
      worker: 192.168.29.118

  glusterfs:
    description: >
      GlusterFS volume must be created and mounted identically
      on all nodes using hostPath.
    mount_paths:
      mariadb: /mnt/gv0/data/mariadb
      nextcloud: /mnt/gv0/data/nextcloud

  kubernetes_tools:
    - kubectl
    - kubeconfig configured at ~/.kube/config


# SECTION 2: PERSISTENT VOLUMES (GLUSTERFS BACKED)

# Persistent Volume for MariaDB
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mariadb-pv
spec:
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/gv0/data/mariadb
    # GlusterFS volume mounted on all nodes


---

# Persistent Volume Claim for MariaDB
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mariadb-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 3Gi


# SECTION 3: MARIADB DEPLOYMENT

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb
spec:
  # Original HA design: replicas = 3
  # Actual deployment: replicas = 1 (single worker limitation)
  replicas: 1
  selector:
    matchLabels:
      app: mariadb
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
        - name: mariadb
          image: mariadb:10.6
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "<ENTER_ROOT_PASSWORD>"
            - name: MYSQL_DATABASE
              value: nextcloud
            - name: MYSQL_USER
              value: nextclouduser
            - name: MYSQL_PASSWORD
              value: "<ENTER_DB_PASSWORD>"
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: mariadb-vol
              mountPath: /var/lib/mysql
      volumes:
        - name: mariadb-vol
          persistentVolumeClaim:
            claimName: mariadb-pvc


---

# MariaDB Service (Internal Cluster Service)
apiVersion: v1
kind: Service
metadata:
  name: mariadb
spec:
  selector:
    app: mariadb
  ports:
    - port: 3306
      targetPort: 3306


# SECTION 4: NEXTCLOUD STORAGE (GLUSTERFS)

# Persistent Volume for Nextcloud
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nextcloud-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/gv0/data/nextcloud


---

# Persistent Volume Claim for Nextcloud
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi


# SECTION 5: NEXTCLOUD DEPLOYMENT

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextcloud
spec:
  # Original HA design: replicas = 3
  # Actual deployment: replicas = 1
  replicas: 1
  selector:
    matchLabels:
      app: nextcloud
  template:
    metadata:
      labels:
        app: nextcloud
    spec:
      containers:
        - name: nextcloud
          image: nextcloud:27
          env:
            - name: MYSQL_HOST
              value: mariadb
            - name: MYSQL_DATABASE
              value: nextcloud
            - name: MYSQL_USER
              value: nextclouduser
            - name: MYSQL_PASSWORD
              value: "<ENTER_DB_PASSWORD>"
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nextcloud-vol
              mountPath: /var/www/html
      volumes:
        - name: nextcloud-vol
          persistentVolumeClaim:
            claimName: nextcloud-pvc



# SECTION 6: NEXTCLOUD SERVICE (NODEPORT)

apiVersion: v1
kind: Service
metadata:
  name: nextcloud-service
spec:
  selector:
    app: nextcloud
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080
      # Access URL:
      # http://<NodeIP>:30080


# SECTION 7: DEPLOYMENT COMMAND

deployment_command: |
  kubectl apply -f nextcloud-k3s-glusterfs-deployment.yaml

